# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # - on schedule, every 4 hours
  #schedule:
   # - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository, so it can read the files inside it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # Fetch the dataset, write the data to json files and push the files to the repo
      - name: Fetch and write data
        uses: treecg/LDES-Action@main
        with:
          gh_pages_url: 'pieter.pm/coghent-substrings'
          datasource_strategy: 'ldes-client'
          # url you want to fetch
          url: 'https://apidgdv.gent.be/opendata/adlib2eventstream/v1/adlib/personen'
          # output directory name
          storage: 'personen'
          fragmentation_strategy: 'substring'
          fragmentation_page_size: 20
          property_path: '<https://data.vlaanderen.be/ns/persoon#volledigeNaam>'
          stream_data: "true"
